# Generated by Django 4.1.6 on 2023-02-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('important', 'Important'), ('dontForget', 'Dont Forget')], default='important', max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
